language: python
python:
  - "3.7"
  - "3.9"
# Cache pip packages for us so builds are faster
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python -Wa manage.py test --keepdb
