version: "3.9"
   
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'zues'
      MYSQL_USER: 'jd'
      MYSQL_PASSWORD: 'jd2021!'
      MYSQL_ROOT_PASSWORD: 'jd2021'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db