# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuelePolitiekeMotie',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ingediend'), (2, b'Verwijderd'), (3, b'Repareren'), (4, b'Geaccepteerd'), (5, b'Publiek')])),
                ('admin_opmerkingen', models.TextField(help_text=b'Opmerkingen van de beheerder', blank=True)),
                ('boeknummer', models.IntegerField(blank=True)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende paragraaf', blank=True)),
                ('constateringen', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet', blank=True)),
                ('overwegingen', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet', blank=True)),
                ('uitspraken', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet')),
            ],
            options={
                'ordering': ('-laatsteupdate',),
                'verbose_name_plural': 'actuele politieke moties',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Amendement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ingediend'), (2, b'Verwijderd'), (3, b'Repareren'), (4, b'Geaccepteerd'), (5, b'Publiek')])),
                ('admin_opmerkingen', models.TextField(help_text=b'Opmerkingen van de beheerder', blank=True)),
                ('boeknummer', models.IntegerField(blank=True)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende paragraaf', blank=True)),
                ('betreft', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=2, choices=[(b'W', b'Wijzigen'), (b'S', b'Schrappen'), (b'T', b'Toevoegen')])),
                ('tekst1', models.TextField()),
                ('tekst2', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'amendementen',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('prefix', models.CharField(unique=True, max_length=50)),
                ('titel', models.CharField(max_length=250)),
                ('index', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'categorieen',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HRWijziging',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ingediend'), (2, b'Verwijderd'), (3, b'Repareren'), (4, b'Geaccepteerd'), (5, b'Publiek')])),
                ('admin_opmerkingen', models.TextField(help_text=b'Opmerkingen van de beheerder', blank=True)),
                ('boeknummer', models.IntegerField(blank=True)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende paragraaf', blank=True)),
                ('betreft', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=2, choices=[(b'W', b'Wijzigen'), (b'S', b'Schrappen'), (b'T', b'Toevoegen')])),
                ('tekst1', models.TextField()),
                ('tekst2', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Categorie', null=True)),
            ],
            options={
                'verbose_name_plural': 'HR-wijzigingen',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('naam', models.CharField(max_length=250)),
                ('lidnummer', models.IntegerField(serialize=False, primary_key=True)),
                ('secret', models.CharField(max_length=250)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Organimo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ingediend'), (2, b'Verwijderd'), (3, b'Repareren'), (4, b'Geaccepteerd'), (5, b'Publiek')])),
                ('admin_opmerkingen', models.TextField(help_text=b'Opmerkingen van de beheerder', blank=True)),
                ('boeknummer', models.IntegerField(blank=True)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende paragraaf', blank=True)),
                ('constateringen', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet', blank=True)),
                ('overwegingen', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet', blank=True)),
                ('uitspraken', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Categorie', null=True)),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Login', null=True)),
            ],
            options={
                'ordering': ('-laatsteupdate',),
                'verbose_name_plural': 'organimos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PolitiekeMotie',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ingediend'), (2, b'Verwijderd'), (3, b'Repareren'), (4, b'Geaccepteerd'), (5, b'Publiek')])),
                ('admin_opmerkingen', models.TextField(help_text=b'Opmerkingen van de beheerder', blank=True)),
                ('boeknummer', models.IntegerField(blank=True)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende paragraaf', blank=True)),
                ('constateringen', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet', blank=True)),
                ('overwegingen', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet', blank=True)),
                ('uitspraken', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende bullet')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Categorie', null=True)),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Login', null=True)),
            ],
            options={
                'ordering': ('-laatsteupdate',),
                'verbose_name_plural': 'politieke moties',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Resolutie',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ingediend'), (2, b'Verwijderd'), (3, b'Repareren'), (4, b'Geaccepteerd'), (5, b'Publiek')])),
                ('admin_opmerkingen', models.TextField(help_text=b'Opmerkingen van de beheerder', blank=True)),
                ('boeknummer', models.IntegerField(blank=True)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(help_text=b'Gebruik een dubbele enter voor de volgende paragraaf', blank=True)),
                ('betreft', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=2, choices=[(b'W', b'Wijzigen'), (b'S', b'Schrappen'), (b'T', b'Toevoegen')])),
                ('tekst1', models.TextField()),
                ('tekst2', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Categorie', null=True)),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Login', null=True)),
            ],
            options={
                'verbose_name_plural': 'resoluties',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tijden',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pm_start', models.DateTimeField(null=True, blank=True)),
                ('pm_stop', models.DateTimeField(null=True, blank=True)),
                ('apm_start', models.DateTimeField(null=True, blank=True)),
                ('apm_stop', models.DateTimeField(null=True, blank=True)),
                ('org_start', models.DateTimeField(null=True, blank=True)),
                ('org_stop', models.DateTimeField(null=True, blank=True)),
                ('res_start', models.DateTimeField(null=True, blank=True)),
                ('res_stop', models.DateTimeField(null=True, blank=True)),
                ('am_start', models.DateTimeField(null=True, blank=True)),
                ('am_stop', models.DateTimeField(null=True, blank=True)),
                ('hr_start', models.DateTimeField(null=True, blank=True)),
                ('hr_stop', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'tijden',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='hrwijziging',
            name='eigenaar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Login', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='amendement',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Categorie', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='amendement',
            name='eigenaar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Login', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='actuelepolitiekemotie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Categorie', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='actuelepolitiekemotie',
            name='eigenaar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='zues.Login', null=True),
            preserve_default=True,
        ),
    ]
