# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import zues.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuelePolitiekeMotie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Ingediend'), (2, 'Verwijderd'), (3, 'Repareren'), (4, 'Geaccepteerd'), (5, 'Publiek')], default=1)),
                ('admin_opmerkingen', models.TextField(blank=True, help_text='Opmerkingen van de beheerder')),
                ('boeknummer', models.IntegerField(blank=True, default=0)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende paragraaf')),
                ('constateringen', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('overwegingen', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('uitspraken', models.TextField(help_text='Gebruik een dubbele enter voor de volgende bullet')),
            ],
            options={
                'ordering': ('-laatsteupdate',),
                'verbose_name_plural': 'actuele politieke moties',
            },
        ),
        migrations.CreateModel(
            name='Amendement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Ingediend'), (2, 'Verwijderd'), (3, 'Repareren'), (4, 'Geaccepteerd'), (5, 'Publiek')], default=1)),
                ('admin_opmerkingen', models.TextField(blank=True, help_text='Opmerkingen van de beheerder')),
                ('boeknummer', models.IntegerField(blank=True, default=0)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende paragraaf')),
                ('betreft', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('W', 'Vervangen'), ('S', 'Schrappen'), ('T', 'Toevoegen')], max_length=2)),
                ('tekst1', models.TextField()),
                ('tekst2', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'amendementen',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50)),
                ('titel', models.CharField(max_length=250)),
                ('index', models.IntegerField()),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'categorieen',
            },
        ),
        migrations.CreateModel(
            name='HRWijziging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Ingediend'), (2, 'Verwijderd'), (3, 'Repareren'), (4, 'Geaccepteerd'), (5, 'Publiek')], default=1)),
                ('admin_opmerkingen', models.TextField(blank=True, help_text='Opmerkingen van de beheerder')),
                ('boeknummer', models.IntegerField(blank=True, default=0)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende paragraaf')),
                ('betreft', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('W', 'Vervangen'), ('S', 'Schrappen'), ('T', 'Toevoegen')], max_length=2)),
                ('tekst1', models.TextField()),
                ('tekst2', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Categorie')),
            ],
            options={
                'verbose_name_plural': 'HR-wijzigingen',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=250)),
                ('lidnummer', models.IntegerField()),
                ('secret', models.CharField(max_length=250)),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Ingediend'), (2, 'Verwijderd'), (3, 'Repareren'), (4, 'Geaccepteerd'), (5, 'Publiek')], default=1)),
                ('admin_opmerkingen', models.TextField(blank=True, help_text='Opmerkingen van de beheerder')),
                ('boeknummer', models.IntegerField(blank=True, default=0)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende paragraaf')),
                ('constateringen', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('overwegingen', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('uitspraken', models.TextField(help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Categorie')),
                ('eigenaar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Login')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('-laatsteupdate',),
                'verbose_name_plural': 'organimos',
            },
        ),
        migrations.CreateModel(
            name='PolitiekeMotie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Ingediend'), (2, 'Verwijderd'), (3, 'Repareren'), (4, 'Geaccepteerd'), (5, 'Publiek')], default=1)),
                ('admin_opmerkingen', models.TextField(blank=True, help_text='Opmerkingen van de beheerder')),
                ('boeknummer', models.IntegerField(blank=True, default=0)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende paragraaf')),
                ('constateringen', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('overwegingen', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('uitspraken', models.TextField(help_text='Gebruik een dubbele enter voor de volgende bullet')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Categorie')),
                ('eigenaar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Login')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('-laatsteupdate',),
                'verbose_name_plural': 'politieke moties',
            },
        ),
        migrations.CreateModel(
            name='Resolutie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Ingediend'), (2, 'Verwijderd'), (3, 'Repareren'), (4, 'Geaccepteerd'), (5, 'Publiek')], default=1)),
                ('admin_opmerkingen', models.TextField(blank=True, help_text='Opmerkingen van de beheerder')),
                ('boeknummer', models.IntegerField(blank=True, default=0)),
                ('indienmoment', models.DateField(auto_now_add=True)),
                ('laatsteupdate', models.DateField(auto_now=True)),
                ('secret', models.CharField(max_length=250)),
                ('indieners', models.TextField()),
                ('woordvoerder', models.CharField(max_length=250)),
                ('toelichting', models.TextField(blank=True, help_text='Gebruik een dubbele enter voor de volgende paragraaf')),
                ('betreft', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('W', 'Vervangen'), ('S', 'Schrappen'), ('T', 'Toevoegen')], max_length=2)),
                ('tekst1', models.TextField()),
                ('tekst2', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Categorie')),
                ('eigenaar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Login')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'resoluties',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=250)),
                ('mededeling', models.CharField(max_length=250)),
                ('public', models.BooleanField(default=False)),
                ('pm_start', models.DateTimeField(blank=True, null=True)),
                ('pm_stop', models.DateTimeField(blank=True, null=True)),
                ('apm_start', models.DateTimeField(blank=True, null=True)),
                ('apm_stop', models.DateTimeField(blank=True, null=True)),
                ('org_start', models.DateTimeField(blank=True, null=True)),
                ('org_stop', models.DateTimeField(blank=True, null=True)),
                ('res_start', models.DateTimeField(blank=True, null=True)),
                ('res_stop', models.DateTimeField(blank=True, null=True)),
                ('am_start', models.DateTimeField(blank=True, null=True)),
                ('am_stop', models.DateTimeField(blank=True, null=True)),
                ('hr_start', models.DateTimeField(blank=True, null=True)),
                ('hr_stop', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.AddField(
            model_name='hrwijziging',
            name='eigenaar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Login'),
        ),
        migrations.AddField(
            model_name='hrwijziging',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='amendement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Categorie'),
        ),
        migrations.AddField(
            model_name='amendement',
            name='eigenaar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Login'),
        ),
        migrations.AddField(
            model_name='amendement',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='actuelepolitiekemotie',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Categorie'),
        ),
        migrations.AddField(
            model_name='actuelepolitiekemotie',
            name='eigenaar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zues.Login'),
        ),
        migrations.AddField(
            model_name='actuelepolitiekemotie',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterModelManagers(
            name='actuelepolitiekemotie',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='amendement',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='categorie',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hrwijziging',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='login',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='organimo',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='politiekemotie',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resolutie',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='settings',
            managers=[
                ('objects', zues.utils.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='actuelepolitiekemotie',
            name='onderwerp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='amendement',
            name='onderwerp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hrwijziging',
            name='onderwerp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organimo',
            name='onderwerp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='politiekemotie',
            name='onderwerp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resolutie',
            name='onderwerp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'categorieën'},
        ),
        migrations.AlterModelOptions(
            name='organimo',
            options={'ordering': ('-laatsteupdate',), 'verbose_name_plural': "organimo's"},
        ),
        migrations.AlterField(
            model_name='actuelepolitiekemotie',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='amendement',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='hrwijziging',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='login',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='organimo',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='politiekemotie',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='resolutie',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
