# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('begintijd', models.DateTimeField()),
                ('eindtijd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'dagen',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'locaties',
            },
        ),
        migrations.CreateModel(
            name='Nieuwsitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('tekst', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'nieuwsitems',
            },
        ),
        migrations.AddField(
            model_name='activiteit',
            name='dag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appolo.Dag'),
        ),
        migrations.AddField(
            model_name='activiteit',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appolo.Locatie'),
        ),
        migrations.AlterModelOptions(
            name='activiteit',
            options={'verbose_name_plural': 'activiteiten'},
        ),
        migrations.AlterField(
            model_name='activiteit',
            name='dag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appolo.Dag'),
        ),
        migrations.AlterField(
            model_name='activiteit',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appolo.Locatie'),
        ),
    ]
