# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appolo', '0002_metachanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiteit',
            name='dag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appolo.Dag'),
        ),
        migrations.AlterField(
            model_name='activiteit',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appolo.Locatie'),
        ),
    ]
